# The start symbol is START.

# These two rules are required; choose their weights carefully!
99	START	S1
30	START	SQ
0	START	S2

# This is a very, very, very simple grammar to get you started.

10	S1	NP VP .
1	S1	NP VP !

10	SQ	do NP VP ?
10	SQ	dooes NP VP ?
10	SQ	are NP VP ?
10	SQ	is NP VP ?

1	VP	VerbT NP
1	VP	VerbT AJTP

20	NP	Det Nbar
10	NP	Nbar
1	NP	Proper
1	NP	Place

1	AJTP	JJ

20	Nbar	Noun
10	Nbar	VBG
1	Nbar	Nbar PP

1	PP	Prep NP
1	PP	TO NP
